apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: queue-master
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: queue-master
    spec:
      containers:
      - image: tarasglek/queue
        name: queue-master
        env:
        - name: QUEUE_CONFIG
          value: "postgres://postgres:taras@fs66-b-app/postgres"